language: rust
sudo: false

cache:
  - cargo

rust:
  - stable


before_script:
  - (test -x $HOME/.cargo/bin/mdbook || cargo install mdbook)


script:
  - mdbook build

deploy:
  provider: pages
  overwrite: true
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  repo: rust-spandex/rust-spandex.github.io
  target_branch: master
  local_dir: book
  on:
    branch: master

notifications:
  email:
    on_success: never
    on_failure: always
